### ISSUE TITLE
[Feature ask] 在群聊显示非好友用户名

### ISSUE THREAD

**Issue by nelwang** [ehForwarderBot/efb-wechat-comwechat-slave#20]
首先感谢作者发布这么好用的产品。

现在碰到的一个问题是如果把群聊绑定到tg的一个group，非好友发消息是会显示wxid，希望能显示非好友的姓名，这样体验会好一点。否则需要切到微信看到底是谁发的消息。

Debug log如下，的确里面只有wxid没有用户名。
comwechat - DEBUG - group_msg:{'extrainfo': '<msgsource>\n\t<atuserlist><![CDATA[wxid_*****]]></atuserlist>\n\t<alnode>\n\t\t<cf>5</cf>\n\t\t<inlenlist>15,15</inlenlist>\n\t</alnode>\n\t<silence>1</silence>\n\t<membercount>315</membercount>\n\t<signature>v1_XtkShUpr</signature>\n</msgsource>\n', 'filepath': '', 'isSendMsg': 0, 'message': '*****', 'msgid': 6276896509010873515, 'pid': 32, 'self': 'a31065312', 'sender': '384181767@chatroom', 'sign': 'cbad05b9dbe138f795225b0ab24c035a', 'thumb_path': '', 'time': '2023-02-16 05:11:52', 'timestamp': 1676524312, 'type': 'text', 'wxid': 'wxid_*****'}

**Comment by 0honus0** [comment]
这个用户可能是刚加群的，数据库中没有对应信息，可能需要过一段时间更新
